---
version: '3.7'
services:
 devserver:
  image: jenkins
  restart: always
  ports:
   - 5050:8080
  deploy:
   placement:
    constraints:
     - node.hostname == Manager
 qaserver:
  image: tomcat
  restart: always
  ports:
   - 6060:8080
  deploy:
   replicas: 4
   placement:
    constraints:
     - node.hostname == worker1 

 prodserver:
  image: tomcat
  restart: always
  ports:
   - 7070:8080
  deploy:
   replicas: 3
   placement:
    constraints:
     - node.hostname == Worker2
...
