---
version: '3.7'
services:
 devserver:
  image: jenkins
  restart: always
  ports:
   - 5050:8080
 qaserver:
  image: tomcat
  restart: always
  ports:
   - 6060:8080
  links:
   - devserver:jenkins
 prodserver:
  image: tomcat
  restart: always
  ports:
   - 7070:8080
  links:
   - devserver:jenkins
...
